baseURL = "https://unicef.github.io/drone-4sdgtoolkit"
languageCode = "en-us"
title = "Drone DPG Toolkit"
theme = "inventory"
enableEmoji = true
enableGitInfo = true

# Google Analytics
googleAnalytics = ""

# Allow unsafe HTML
[markup.goldmark.renderer]
unsafe = true


############################# Navigation #############################
[[menu.main]]
weight = 10
name = "FAQ"
url = "faq"

[[menu.main]]
weight = 20
name = "pages"
url = "pages"
hasChildren = true

[[menu.main]]
    parent = "pages"
    name = "Analytics"
    url = "analytics"
    weight = 10

    [[menu.main]]
    parent = "pages"
    name = "Guides"
    url = "guides"
    weight = 20

    [[menu.main]]
    parent = "pages"
    name = "Learning"
    url = "learning"
    weight = 30

    [[menu.main]]
    parent = "pages"
    name = "REGs"
    url = "regs"
    weight = 40

    [[menu.main]]
    parent = "pages"
    name = "Software"
    url = "software"
    weight = 50

    [[menu.main]]
    parent = "pages"
    name = "Startups"
    url = "startups"
    weight = 60





############################# Default parameters #############################
[params]
logo = "images/unicef-logo.png"

# OpenGraph / Twitter Card metadata
description = "Toolkit of drones-for-public-good resources including text, image, video and audio content, and Open Source software, code, libraries, and training datasets."
author = "Edmond Nonie, UNICEF Office of Innovation, and others"
image = "images/UNI309823.jpg"

# customize color
primary_color = "#1CABE2"
body_color = "#D8D1C9"
text_color = "#777779"
text_color_dark = "#374EA2"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family (choose from https://fonts.google.com/)
font_family = "Open+Sans"

# related article number limit
article_count = 3

############################# Contact forms #############################
# All contact forms work with https://formspree.io

contact_form_action = "#"

[params.rsvp_form]
action = "https://formspree.io/f/xwkajewy"
message = "How do you work with drones?"


############################# Social links #############################
# themify icon pack : https://themify.me/themify-icons

[[params.social]]
icon = "ti-github"
name = "UNICEF Drone DPG Toolkit on GitHub"
link = "https://github.com/unicef/drone-4sdgtoolkit"

[[params.social]]
icon = "ti-twitter"
name = "@UNICEFinnovate on Twitter"
link = "https://twitter.com/UNICEFinnovate"

[params.footer]
mainSite = "https://www.unicef.org/innovation/drones"
mainSiteName = "Drones at UNICEF Innovation"
description = "The UNICEF Drone DPG Toolkit is a toolkit of drones-for-public-good resources including text, image, video and audio content, and open-source software, code, libraries, and training datasets. The Drone DPG Toolkit includes Standard Operating Procedures and regulations documents for drone operations, open-learning material and online courses for drones, Open Source software for drones, Open Source a.i. training datasets for various drone data use cases, decision-making guides, how-to guides, and company information for drone companies or other entities implementing open source drone DPG solutions."


############################# Markup tweaks and customization #############################
[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'murphy'
tabWidth = 4

[markup.asciidocExt]
preserveTOC = true
sectionNumbers = true

############################# Related Articles #############################
[taxonomies]
  category = "categories"
  downloadable = "downloadBtn"


#######################################################################################
#                             Multilingual configurations                             #
#######################################################################################

############################# English #############################
[Languages.en]
languageName = "en"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Creative Commons BY-SA 4.0. Site theme maintained by UNICEF. Original theme, Dot, created by ThemeFisher."

# banner
[Languages.en.params.banner]
title = "UNICEF Drone DPG Toolkit"
subtitle = "A UNICEF Innovation toolkit of drones-for-public-good resources including text, image, video and audio content, and Open Source software, code, libraries, and training datasets."
bg_image = "images/banner.jpg"
placeholder = "Have a question? Search the site here."
